config/routes.rb
unless !!ENV['si']
  Rails.application.routes.draw do
    mount Attachable::Engine => "", as: "attachable"#, subdomain: "assets"

    mount Ckeditor::Engine => '/ckeditor'
    devise_for :users, class_name: "User"

    devise_scope :user do
      get "/logout", to: "devise/sessions#destroy"
    end

    constraints subdomain: "crm" do

      RailsAdminRouter.load(self)
    end

    namespace "crm", module: "crm", path: "/" do
      root to: "dashboard#index"
      resources :complexes
      resources :apartment_houses
      resources :apartments
    end

    concern :commentable do
      resources :comments
    end

    concern :assetable do
      resources :assets
    end

    root to: "rails_admin/main#index"
    match "*path", to: "errors#not_found", via: [:get, :post, :update, :put, :delete]

  end
end

app/controllers/crm/administrators_controller.rb
class Crm::AdministratorsController < Crm::MainController


  def list_entries(*args)
    #super(*args).administrators
    Sigma::Manager.administrators
  end
end

app/controllers/crm/apartment_houses_controller.rb
module Crm
  class ApartmentHousesController < ResourcesController

  end
end

app/controllers/crm/apartments_controller.rb
module Crm
  class ApartmentsController < ResourcesController

  end
end

app/controllers/crm/complexes_controller.rb
module Crm
  class ComplexesController < ResourcesController

  end
end

app/controllers/crm/dashboard_controller.rb
module Crm
  class DashboardController < ApplicationController
    before_action :authenticate_account!, unless: :json_request?

    def index

    end
  end
end

app/controllers/crm/main_controller.rb
class Crm::MainController < RailsAdmin::MainController

  # before_action :initialize_before_action
  #
  # def initialize_before_action
  #   action = RailsAdmin::Config::Actions.find("#{params[:action]}".to_sym)
  #   @authorization_adapter.try(:authorize, action.authorization_key, @abstract_model, @object)
  #   @action = action.with({controller: self, abstract_model: @abstract_model, object: @object})
  #   fail(ActionNotAllowed) unless @action.enabled?
  #   @page_name = wording_for(:title)
  # end
  #
  #
  # def model
  #   @model ||= @abstract_model.model
  # end

  def list_entries *args
    #entries = super
    #entries.where("role is null")
    super(*args)
  end



  # def index
  #
  # end
  #
  # def edit
  #
  # end
  #
  # def create
  #
  # end
  #
  # def show
  #
  # end
end

app/controllers/crm/managers_controller.rb
class Crm::ManagersController < Crm::MainController
  # def invite
  #   #super
  #   if request.get?
  #     @resource = model.new
  #
  #     @resource_permissions = @resource.user_permissions
  #   end
  # end

  def list_entries(*args)
    super(*args)#.managers
  end
end

app/controllers/crm/resources_controller.rb
module Crm
  class ResourcesController < ::ResourcesController
    #before_action :authenticate_account!, unless: :json_request?
    before_action :configure_fields, :configure_actions

    def index
      @resources ||= resource_class.all.page(params[:page])
    end

    def resources_path_name
      "crm_#{super}"
    end

    def resource_path_name
      "crm_#{super}"
    end

    def resource_class_name
      super["Crm::".length, super.length]
    end

    def configure_fields
      @fields ||= []
    end

    def configure_actions
      @actions = [:index, :new, :edit, :delete]
    end
  end
end

app/controllers/crm/super_administrators_controller.rb
class Crm::SuperAdministratorsController < Crm::MainController
  def list_entries(*args)
    #super.super_administrators
    #Sigma::Manager.all.super_administrators
    Sigma::Manager.super_administrators
  end
end

app/controllers/crm_controller.rb
class CrmController < ApplicationController
  #before_action :authenticate_account!, unless: :json_request?
  #before_action :fill_user_profile, unless: :json_request?
  #before_action :create_breadcrumbs

  before_action :init_variables

  self.layout "crm"

  def skin_config
    render template: "layouts/skin_config.html.slim", layout: false
  end

  private

  def create_breadcrumbs
    @breadcrumbs = []
  end

  # def my_authenticate_user!
  #   if current_user.nil?
  #     redirect_to new_user_session_path
  #   end
  # end

  def fill_user_profile
    if current_user.profile_status.unfilled?
      user_role_name = current_user.class.name.underscore
      redirect_to send("edit_#{user_role_name}_registration_path")
    end
  end

  def init_variables
    @included_models = []
  end

end

app/helpers/crm_helper.rb
class Form

end

module CrmHelper
  extend SimpleForm::ActionViewExtensions::FormHelper
  def simple_form_with_context record, options = {}, &block
    simple_form_for record, options, &block
  end

  def my_simple_form_for &block
    f = Form.new
    f.instance_eval

  end
end

app/views/crm/_dynamic_navigation.html.slim
.navigation
  - navigation_menu.each do |item|
    li
      = link_to item, resources_path(resource_class: item)

app/views/crm/_form.html.slim
.info
  = @fields.map{|f| compute_field_config(f[:name]) }.inspect
= simple_form_for @resource, url: resources_path do |form|
  /- @fields.each do |field|
    - field = compute_field_config(field[:name])
    - if field[:association]
      - if field[:nested]
        = simple_fields_for field[:name] do
      - else
        = form.association field[:name]
    - else
      = form.input field[:name]
  .info
    = render "form_content", form: form

app/views/crm/_form_content.html.slim
= raw render_fields(form).inspect

app/views/crm/_navigation.html.slim
.navigation
  ul
    li
      .menu-item-header
        = "Нерухомість"
      ul
        li
          = link_to "Житлові комплекси", crm_complexes_path
        li
          = link_to "Багатоквартирні будинки", crm_apartment_houses_path
        li
          = link_to "Квартири", crm_apartments_path

app/views/crm/dashboard.html.slim
= CrmAdminController.call_me
= my_simple_form_for

app/views/crm/index.html.slim
.actions
  ul.button-group
    li
      = link_to t("activerecord.models.#{resource_name}.new"), new_resource_path, class: "button"
table
  thead
    - @fields.each do |f|
      th
        = f[:name]
  tbody
    - @resources.each do |r|
      tr
        - @fields.each do |f|
          td
            = r.send(f[:name])
        td.actions
          = link_to "show", show_resource_path(r)
          /= link_to "edit", edit_resource_path(r)
          /= link_to "delete", resource_path(r)
= paginate @resources

app/views/crm/new.html.slim
= render "form"